### ISSUE TITLE
[CRASH] - Crash when selecting server

### ISSUE THREAD

**Issue by Unreeling8562** [CappielloAntonio/tempo#139]
## Description
App is crashing when selecting server. Issue is the same when logging in trough other users. No issues on other device/other Android profile

## Steps to Reproduce
1. Open the app and give notification permission.
2. Click on "+"
3. Fill in server details and click on "save"
4. Click on the server that you just added.
5. Crash

## Environment
 - Android device: Google Pixel 6
 - Android OS version: GrapheneOS, android 14
 - App version: 3.6.0
 - Other relevant details: 

## Crash Logs/Stack trace
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.240105.002/2024010400:user/release-keys
package: com.cappielloantonio.tempo:23
process: com.cappielloantonio.tempo
processUptime: 27266 + 214 ms
installer: com.android.packageinstaller

java.lang.IllegalArgumentException: com.cappielloantonio.tempo: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3070)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6612)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:578)
	at android.app.PendingIntent.getActivity(PendingIntent.java:559)
	at android.app.PendingIntent.getActivity(PendingIntent.java:523)
	at i7.e.b(SourceFile:116)
	at i7.s.m(SourceFile:145)
	at i7.s.k(SourceFile:95)
	at i7.s.l(SourceFile:57)
	at i7.e.handleMessage(SourceFile:1021)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5409)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5352)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3274)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2767)
	at android.os.Binder.execTransactInternal(Binder.java:1387)


```

## Additional Context
-

## Reproducibility
Always

## Additional Notes
-

**Comment by GallowsDove** [comment]
Hey, thanks for the bug report!

I've got the exact same device (Pixel 6, GrapheneOS, android 14) and, unfortunately, I can't replicate the issue.
Please provide more information, such as what server/version were you trying to connect to. Does this also happen when you input wrong url? (e.g. does it crash when you put https://example.com as url?)

**Comment by CappielloAntonio** [comment]
Hi @Unreeling8562 , thanks for reporting. 

Would it be possible to capture another crash log with the app version attached in this comment? Unfortunately, your log was captured with a version of the app signed with the release keys, so it's impossible to understand what may have happened. 

Thanks for your patience!

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/14077827/app-tempo-debug.zip)

**Comment by vinter-wu** [comment]
I have the same problem.
Android device: Samsung Filp 5
Android OS version: OneUI 6.0, android 14
App version: 3.7.0/3.6.0
Other relevant details:

**Comment by inknos** [comment]
Hey, could you try with Google services on/off? I have gservices disabled on my phone, and I am hitting the bug. When I enable them (it's possible via Graphene) I don't reproduce the bug.
