### ISSUE TITLE
[CRASH] -  keep getting this crash recently

### ISSUE THREAD

**Issue by ghost** [CappielloAntonio/tempo#290]
On grapheneOS I keep getting this crash recently, maybe after the last OS update:

ype: crash
osVersion: google/shiba/shiba:14/AP2A.240905.003/2024090400:user/release-keys
package: com.cappielloantonio.notquitemy.tempo:25
process: com.cappielloantonio.notquitemy.tempo
processUptime: 11323 + 511 ms
installer: com.android.packageinstaller

java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.card.MaterialCardView f2.g.w' on a null object reference in method 'void androidx.fragment.app.p.b(java.util.List)'
	at androidx.fragment.app.p.b(SourceFile:163)
	at androidx.fragment.app.p.a(SourceFile:141)
	at androidx.lifecycle.z.b(SourceFile:30)
	at androidx.lifecycle.z.c(SourceFile:56)
	at androidx.lifecycle.z.k(SourceFile:15)
	at androidx.lifecycle.B.k(SourceFile:1)
	at j2.c.onResponse(SourceFile:63)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(SourceFile:26)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.b(SourceFile:1)
	at retrofit2.a.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by CappielloAntonio** [comment]
I am closing the issue as the account appears to have been deleted
