### ISSUE TITLE
[CRASH] - App crashes when searching genres before the genres list is populated

### ISSUE THREAD

**Issue by vctls** [CappielloAntonio/tempo#308]
## Description
The app crashes when searching genres  before the genres list is populated.

## Steps to Reproduce
1. Go Library
2. Scroll down to Genres (which by the way take a few seconds to show up)
3. Tap See all
4. The genres list is empty
5. Tap the magnifying glass in the upper right corner
6. Start typing _before the list is populated_
7. The app crashes

The genres list takes about 6 seconds to populate. If I simply wait enough time before searching, the app doesn't crash.

## Environment
 - Android device: Fairphone 5
 - Android OS version: 14
 - App version: 3.8.1
 - Other relevant details: using an Ampache v7 server with a pretty big collection

## Crash Logs/Stack trace
```
FATAL EXCEPTION: main
Process: com.cappielloantonio.notquitemy.tempo, PID: 9098
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Collection.iterator()' on a null object reference
	at java.util.AbstractCollection.addAll(AbstractCollection.java:335)
	at R.d.publishResults(SourceFile:85)
	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
```

## Reproducibility
always

## Additional Notes
I suppose the issue is pretty obvious. The genres collection seems to be null until it gets populated. Trying to search before that results in a NullPointerException.  
I'm not sure how the genres list is generated, but it doesn't seem to be cached. The list is initially empty each time I tap "See all".  
Maybe there's some server configuration that might help with that?

**Comment by CappielloAntonio** [comment]
Thank you, it's now fixed!
