### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by C9Glax** [CappielloAntonio/tempo#69]
When starting, screen briefly shows albums, etc. then crashes.

```
type: crash
osVersion: google/oriole/oriole:13/TQ3A.230805.001/2023090600:user/release-keys
package: com.cappielloantonio.tempo:19
process: com.cappielloantonio.tempo
processUptime: 26616 + 239 ms
installer: com.machiav3lli.fdroid

java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at i5.a.onResponse(SourceFile:56)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(SourceFile:26)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.b(SourceFile:1)
	at retrofit2.a.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by C9Glax** [comment]
Happens only after the latest android update

**Comment by CappielloAntonio** [comment]
Hello @C9Glax, unfortunately this log was taken with the app signed with release keys. Could you reproduce the problem with this apk and take another crash log?

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/12557634/app-tempo-debug.zip)

**Comment by C9Glax** [comment]
Sure!

```
type: crash
osVersion: google/oriole/oriole:13/TQ3A.230805.001/2023090600:user/release-keys
package: com.cappielloantonio.tempo:20
process: com.cappielloantonio.tempo
processUptime: 1414 + 59 ms
installer: com.android.packageinstaller

java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.cappielloantonio.tempo.repository.AlbumRepository$10.onResponse(AlbumRepository.java:253)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

**Comment by CappielloAntonio** [comment]
Thanks a lot! 
Fixed! Soon I'll send you a test build to test whether the problem is really solved.

**Comment by CappielloAntonio** [comment]
Here you go!

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/12559684/app-tempo-debug.zip)

**Comment by C9Glax** [comment]
Works great cheers!
