### ISSUE TITLE
Crash when searching while server is down

### ISSUE THREAD

**Issue by GallowsDove** [CappielloAntonio/tempo#78]
Reverse proxy returns a 404.
edit: also happens when the device doesn't have internet connection

```
type: crash
osVersion: google/oriole/oriole:13/TQ3A.230805.001/2023090600:user/release-keys
package: com.cappielloantonio.notquitemy.tempo:1
process: com.cappielloantonio.notquitemy.tempo
processUptime: 6885 + 79 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'com.cappielloantonio.tempo.subsonic.models.SubsonicResponse com.cappielloantonio.tempo.subsonic.base.ApiResponse.getSubsonicResponse()' on a null object reference
	at com.cappielloantonio.tempo.repository.SearchingRepository$2.onResponse(SearchingRepository.java:60)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by GallowsDove** [comment]
It would be nice to add some message informing user that the search failed, but the crash seems fixed, and since that is another issue, I'm going to close this one
