### ISSUE TITLE
[CRASH] - app just randomly crashes sometimes

### ISSUE THREAD

**Issue by oopsitsdeleted** [CappielloAntonio/tempo#96]
It just randomly happens sometimes

## Environment
 - Android device: Nothing (1)
 - Android OS version: 13
 - App version: 3.5.7
 - Other relevant details:

## Crash Logs/Stack trace

  | time: 1696505190236
-- | --
  | msg: java.lang.NullPointerException: Attempt to read from field 'android.view.View e5.m.i' on a null object reference in method 'void d6.s0.run()'
  | stacktrace: java.lang.NullPointerException: Attempt to read from field 'android.view.View e5.m.i' on a null object reference in method 'void d6.s0.run()'
  | at d6.s0.run(SourceFile:45)
  | at android.os.Handler.handleCallback(Handler.java:942)
  | at android.os.Handler.dispatchMessage(Handler.java:99)
  | at android.os.Looper.loopOnce(Looper.java:201)
  | at android.os.Looper.loop(Looper.java:288)
  | at android.app.ActivityThread.main(ActivityThread.java:7964)
  | at java.lang.reflect.Method.invoke(Native Method)
  | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by CappielloAntonio** [comment]
Hi @oopsitsdeleted, I'm sorry to hear that. 

As can be seen, the log does not contain useful information as it was captured using the signed apk. To ensure that I have a starting point from which to fix the bug, could you use `app-tempo-debug.apk`? 

You can always find it in the [Release](https://github.com/CappielloAntonio/tempo/releases) section, thank you.

**Comment by tatamiboy** [comment]
I'm also having random crashes as well.
Android 12, app version is 3.5.7 (debug).
The crash log is below.

```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.cappielloantonio.tempo, PID: 3176
AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
AndroidRuntime:        at java.util.ArrayList.addAll(ArrayList.java:677)
AndroidRuntime:        at com.cappielloantonio.tempo.viewmodel.AlbumCatalogueViewModel$2.onResponse(AlbumCatalogueViewModel.java:66)
AndroidRuntime:        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
AndroidRuntime:        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:234)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:346)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8234)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

This is my first time getting crash logs, so please excuse me if I'm wrong.
I looked at other issues and used the command `logcat -b crash`. 
`logcat -b crash -s com.cappielloantonio.tempo` shows nothing.

**Comment by ChinoGoblino** [comment]
I also get frequent crashes if I swap between different menus too quickly or tap a button such as 'home' in quick succession. The app must be navigated very slowly to prevent any crashing. 
Android 14, app version is 3.5.7 (debug)

```
2023-10-29 15:02:37.023 17093-17180 OpenGLRenderer          com.cappielloantonio.tempo           D  --- Failed to create image decoder with message 'unimplemented'                                                                                                                                                                     
2023-10-29 15:02:37.024 17093-17178 OpenGLRenderer          com.cappielloantonio.tempo           D  --- Failed to create image decoder with message 'unimplemented'                                                                                                                                                                     
2023-10-29 15:02:37.027 17093-17180 OpenGLRenderer          com.cappielloantonio.tempo           D  --- Failed to create image decoder with message 'unimplemented'                                                                                                                                                                     
2023-10-29 15:02:37.058 17093-17093 AndroidRuntime          com.cappielloantonio.tempo           D  Shutting down VM                                                                                                                                                                                                                    
2023-10-29 15:02:37.059 17093-17093 AndroidRuntime          com.cappielloantonio.tempo           E  FATAL EXCEPTION: main                                                                                                                                                                                                               
                                                                                                    Process: com.cappielloantonio.tempo, PID: 17093                                                                                                                                                                                     
                                                                                                    java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for LibraryFragment{873318f} (a2893984-97a7-40f5-b71c-ab7631f1ddd9) when getView() is null i.e., before onCreateView() or after onDestroyView()    
                                                                                                    	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:385)                                                                                                                                                      
                                                                                                    	at com.cappielloantonio.tempo.ui.fragment.LibraryFragment.lambda$refreshPlaylistView$13$com-cappielloantonio-tempo-ui-fragment-LibraryFragment(LibraryFragment.java:257)                                                        
                                                                                                    	at com.cappielloantonio.tempo.ui.fragment.LibraryFragment$$ExternalSyntheticLambda6.run(Unknown Source:2)                                                                                                                       
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)                                                                                                                                                                          
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)                                                                                                                                                                          
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)                                                                                                                                                                                  
                                                                                                    	at android.os.Looper.loop(Looper.java:294)                                                                                                                                                                                      
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8199)                                                                                                                                                                    
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                                                               
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)                                                                                                                                            
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                        7)                           
```
Thank you for your work in Tempo!

**Comment by CappielloAntonio** [comment]
Hi guys, sorry for the late response, but this last period has been a bit intense. 
Could you try this new version of the app and tell me if there are other crashes?

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/13260060/app-tempo-debug.zip)

**Comment by ChinoGoblino** [comment]
Hi, I have been using the apk you sent and I have not been able to get it to crash. I find that the debug versions are usually a bit slower than the official releases so they are a bit harder to get them to crash but I am fairly confident that they have been fixed from what I could tell. Thank you for fixing it so quickly!
